name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Setup Postgres
        uses: harmon758/postgresql-actions@v1
        with:
          postgresql db: test_db
          postgresql user: test_user
          postgresql password: testpassword1

      - name: Install dependencies
        run: npm i

      - name: Run Tests
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=testpassword1 npm t

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout and clone repo
          uses: actions/checkout@v2

        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: $({secrets.HEROKU_API_KEY})
            heroku_app_name: $({secrets.HEROKU_APP_NAME})
            heroku_email: $({secrets.HEROKU_EMAIL})
